version: '3.7'

services:
  api:
    container_name: easy-auth-api
    restart: unless-stopped
    build:
      context: .
      target: builder
    command: npm run start:dev
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    links:
      - db:
    networks:
      - webnet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    restart: unless-stopped
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_SCHEMA}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: postgres
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      networks:
        - webnet
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      links:
        - "db:easy-auth-db"
networks:
  webnet:
volumes:
  pgdata:
  pgadmin-data:
